version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: asset_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: asset_mgr
      MYSQL_USER: asset_user
      MYSQL_PASSWORD: asset_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
